### ISSUE TITLE
Any ability to customize err message in Dict if value not present instead of default?

### ISSUE THREAD

**Issue by lud4ik** [Deepwalker/trafaret_forked#26]

**Comment by nimnull** [comment]
Why don't you just catch exception and re-raise it with correct type?
For now I can purpose  just a list of extracted constants with string templates that you can redefine. Cause now there is no ability to pass custom message text to the point when `self._failure(<msg>)` is called.
Take a look of its usage https://github.com/Deepwalker/trafaret/blob/master/trafaret/__init__.py#L712
Any thoughts though?
