### ISSUE TITLE
Merging t.Ditct trafarets

### ISSUE THREAD

**Issue by jettify** [Deepwalker/trafaret_forked#30]
It would be cool feature if we can merge two t.Dict trafarets. 
The use case is following: we have base dict trafaret with base fields say:

``` python
main = t.Dict({
    t.Key('field1'): t.String,
    t.Key('field2'): t.String,
    t.Key('field3'): t.String,
})
```

and we want to create other trafarets with additional fields:

``` python
other = t.Ditct({
    t.Key('other_field1'): t.String,
    t.Key('other_field2'): t.String,
})
```

so we can merge those to dicts like:

``` python
new = Dict.merge(main, other)
```

I am not sure regarding api, but this feature will help with trafarets "inheritance", so we can have base trafarets and ability to create new one with additional fields.

**Comment by asvetlov** [comment]
I support the idea if dict merging with overlapped keys will be forbidden. 
`Dict.merge` looks totally fine.

**Comment by Deepwalker** [comment]
While we have not land this feature, you can use obvious lists or tuples to get this functionality

```
keys = (
    ('other_field1', t.String),
    ('other_field2', t.String),
)

keys2 = (
    ('new_field', t.Int),
)

trafaret1 = t.Dict(dict(keys))
trafaret2 = t.Dict(dict(keys + keys2))
```

**Comment by asvetlov** [comment]
The problem is: you cannot use `t.Key` in workaround, only string names.
Keys should be duplicated internally on merging.
