### ISSUE TITLE
Trafaret 0.5.5 breaks Python 2 Compatibility

### ISSUE THREAD

**Issue by Alphadelta14** [Deepwalker/trafaret_forked#35]
The breaking change can be found here.
https://github.com/Deepwalker/trafaret/commit/7c84f5675fd03ec69580c468b5adb7a7a5508556#diff-b4b8822a6fd189b7f9bb5c08453bbec1R972

To reproduce using Python 2:

```
In [1]: import trafaret as t
  File "trafaret/__init__.py", line 972
    def __init__(self, *args, keys={}, **trafarets):
                                 ^
SyntaxError: invalid syntax
```

**Comment by Deepwalker** [comment]
sorry, fixed in 0.6.1
