### ISSUE TITLE
More detailed error message

### ISSUE THREAD

**Issue by jettify** [Deepwalker/trafaret_forked#36]
It would be nice also include actual value in the error message, something like:

``` python
def check_value(self, value):
    if not isinstance(value, self.type_):
        self._failure("value is not %s instead got %s" % (self.type_.__name__, value))
```

since the first question if you see trafaret error is what was the input value.

**Comment by Deepwalker** [comment]
This is controversial feature — you always have data that was not validated. Can you provide use case?

**Comment by jettify** [comment]
What is controversial about it? this feature could greatly speed up debugging, since you can see actual value supplied to trafaret. 

For instance instead of `str` one supplied `object`, instead of seeing message like:`host is not string`, you get `host is not string, got <Class Foo>`. Which one of those message gives more clue what is wrong with code?

**Comment by Deepwalker** [comment]
made it optional.

**Comment by Deepwalker** [comment]
error.as_dict(value=True)

**Comment by jettify** [comment]
Thanks!
