### ISSUE TITLE
`0.7.4` breaks python2 compatibility

### ISSUE THREAD

**Issue by msull** [Deepwalker/trafaret_forked#46]
https://github.com/Deepwalker/trafaret/commit/2aa39f1a9277fc83055a9826cea7df69123ebb88#diff-b4b8822a6fd189b7f9bb5c08453bbec1R1008

Keyword only args are not supported in python2 (https://www.python.org/dev/peps/pep-3102/). It seems unlikely that a patch level release would break backwards compatibility (and there is still a tox specification for py2), so I'm hoping this was unintentional!

**Comment by Deepwalker** [comment]
Uh, sorry. Thank you for reporting! Definitely must not forget about py2k. 0.7.5
