### ISSUE TITLE
Use CI

### ISSUE THREAD

**Issue by samuelcolvin** [Deepwalker/trafaret_forked#47]
Can I suggest trafaret starts using travis CI.

#46 demonstrates how easy it is to break something without automatic tests.

Also I noticed while working on #45 that there's already a broken docstring test with python 3.5 and there are numerous linting errors in tests.

The current stub `.travis.yml` fill needs a few changes, but running tests should be as simple as `pytest tests`.

**Comment by Deepwalker** [comment]
Added circle ci
