### ISSUE TITLE
add ignore_any and allow_any as kwargs to t.Dict

### ISSUE THREAD

**Issue by samuelcolvin** [Deepwalker/trafaret_forked#51]
Trafaret is great for declaratively defining what data you accept however with deep and complex objects this declarative approach is broken by having to make more calls to the object afterwards to set `ignore_any` and `allow_any`.

It should be possible to define everything about a `t.Dict` when first initialising it, including setting extras and ignore.

**Comment by Deepwalker** [comment]
Not sure about it. We have this Dict interface now — `Dict(*args, **trafarets)`, where args can be `dict|List[trafaret]`. So if we will accept `ignore_any` and `allow_any` we will broke code where this names used for dict keys. Historical mess, probably need to clean up all of this to make 1.0.

**Comment by samuelcolvin** [comment]
I understand about the mess with args and kwargs, particularly as you still support py2.

But surely better to fix it sooner rather than later.

**Comment by Deepwalker** [comment]
Added allow_extra, allow_extra_trafaret and ignore_extra kwargs in 0.9.0
