### ISSUE TITLE
Logging issues for DataError

### ISSUE THREAD

**Issue by hellysmile** [Deepwalker/trafaret_forked#57]
https://github.com/Deepwalker/trafaret/commit/3f8af9c99ab3457d2d0aaf70381578a83913808f

Added `__bool__` to `trafaret.DataError`

```python
try:
    trafaret.Int()('a')
except trafaret.DataError as exc:
    logger.error('Foo', exc_info=exc)
```

DataError message and details will be swallowed by 

https://github.com/python/cpython/blob/master/Lib/logging/__init__.py#L1435

**Comment by Deepwalker** [comment]
And what do you propose? logging code is wrong, it must check exc_info against None, not it falseness.

**Comment by krkd** [comment]
Can you explain use case  for  `DataError.__bool__ ` ?

**Comment by Deepwalker** [comment]
For shortcuts, like `extract_error(t.Int, 'bla') or 5`.
I'm not sure if I must somehow address `logging` issues.

**Comment by hellysmile** [comment]
For logging it is a feature to say `logger.error('XXX', exc_info=True|False)` If You do not specify `exc_info=exc` exception will be found from sys.exc_info(). Boolean behaviour there is for ages and there is no chance to change it. It is very unexpected if You have uncaught exception which body is empty in logs due `DataError.__bool__`

**Comment by hellysmile** [comment]
@Deepwalker hey, do You have any ideas how to solve this issue? We will contribute any Your suggestion. Give us please Your instructions. Thanks.

**Comment by Deepwalker** [comment]
Guys, really, I dont know what to do — actually, really, indeed, this is a bug. In logging. I dont want to throw out good feature just because some line of code in the universe too rigid and dont test False as `is False`.

**Comment by Deepwalker** [comment]
BTW why not use it like exc_info=True? It seems it will use sys.exc_info() and will do the same.
Or maybe feature not so good. Dont know. Have you any arguments to give up on __bool__ despite this is actually not its fault?

**Comment by hellysmile** [comment]
`exc_info=True` generally works, but `sys.exc_info()` is really slow, but it is not critical.  Another question is integration to 3rd party services, for example https://github.com/aio-libs/aiohttp/blob/eee65a4eed846394082c5e931fc75f9c1e7f30cd/aiohttp/web_protocol.py#L521 so  uncaught `DataError` will be swallowed

**Comment by Deepwalker** [comment]
ok, removed feature. but admit it — its logging bug.

**Comment by hellysmile** [comment]
@Deepwalker thanks!
