### ISSUE TITLE
trafaret.Int converts values while checking

### ISSUE THREAD

**Issue by thenx** [Deepwalker/trafaret_forked#69]
`((t.Int() | t.String()) & t.String())('0')`
produces `DataError: value is not a string` which is obviously not true. This also introduces bugs in aiohttp_admin.
`t.Int().check(..., convert=False)` also converts string to int

**Comment by Deepwalker** [comment]
Agree, now. Long time ago was not. BTW what bug you have in aiohttp_admin?
In meantime need to figure out hot to solve this and not hurt compatibility. It seems many rely on this behaviour.

**Comment by thenx** [comment]
aiohttp_admin defines `SimpleType = t.Int | t.Bool | t.String | t.Float` which is used to validate ListQuery and Filters, in particular. During this validation it converts int-like strings to int. Later the filters are created with respect to collection schema. The value gets checked again but it is not string anymore which results in an error.

So a quick example of this error: you have a string column and you are trying to use int-like value in a filter.

**Comment by Deepwalker** [comment]
Actually trafarets are not validators, they are composable converters. For this case we need to create separate Int, which will not convert its value. Like with Regex and RegexRaw.
`convert=False` is deprecated – composability is a key. So for your case I'm going to introduce new trafarets.

**Comment by Deepwalker** [comment]
Check this https://github.com/Deepwalker/trafaret/pull/73

**Comment by Deepwalker** [comment]
Merged. Use t.RawInt instead of t.Int to just check and not convert
