### ISSUE TITLE
Tests fail for python3.3

### ISSUE THREAD

**Issue by tailhook** [Deepwalker/trafaret_forked#8]
The issue with python3.3 (or older versions with PYTHONHASHSEED=random) is different order of keys in doctests. I can see several ways to fix the issue:
1. Migrate tests to `unittest`
2. `from reprlib import repr` and wrap every line with this `repr` (this one sorts keys
3. Hack doctests to use `repr` from `reprlib` rather than builtin

Any other ideas? Preferences?

**Comment by Deepwalker** [comment]
I think we can use second.
Rationale
1. migration to unittest is not fast task, and I dont like unittest lib
3. hack in python sounds strange :) Anyway will investigate a bit later, may be we can use inheritance without hacks.

**Comment by tailhook** [comment]
Fixed with #9
